spring:
  redis:
    host: 127.0.0.1
    password: ''
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: jeecg-demo
          uri: lb://jeecg-demo
          predicates:
            - Path=/mock/**,/test/**
        - id: jeecg-system
          uri: lb://jeecg-system
          predicates:
            - Path=/sys/**,/online/**,/api/**,/webSocketApi/**,/message/**
        - id: jeecg-cloud-websocket
          uri: lb:ws://jeecg-system
          predicates:
            - Path=/websocket/**
management:
  endpoints:
    web:
      exposure:
        include: '*'